### ISSUE TITLE
Set up kanban board 

### ISSUE THREAD

**Issue by Rhaegar121** [Rhaegar121/Recipe-App#14]
In this issue, we have completed the following tasks.

1. Created a new repo 
2. Set up kanban board in project
3. Created new issues for tasks in kanban board

There are two members in our group.
This is the [project link](https://github.com/Rhaegar121/Recipe-App/projects/1)

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Rhaegar121 and @anthonymr,

✔️ Tasks are complete and well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
